
name: tikerama_validateur
description: Application Flutter de validation de tickets Tikerama
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^12.1.3
  
  # Networking
  dio: ^5.4.0
  
  # QR Code Scanner
  mobile_scanner: ^3.5.6
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Light Sensor
  light: ^3.0.1
  
  # Fonts
  google_fonts: ^6.1.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
